//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarizacia.Model.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oborudovanie
    {
        public int ID { get; set; }
        public int InventNom { get; set; }
        public string Naim { get; set; }
        public int Type_obor { get; set; }
        public string Descrip { get; set; }
    
        public virtual Type_oborud Type_oborud { get; set; }
    }
}
